# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('is_approved_by_doctor', models.BooleanField(default=False, verbose_name='تأیید پزشک')),
                ('ecg_type', models.CharField(choices=[('12lead', '۱۲ لید'), ('rhythm', 'ریتم'), ('stress', 'استرس')], max_length=20, verbose_name='نوع نوار')),
                ('patient_position', models.CharField(blank=True, max_length=50, verbose_name='وضعیت بیمار هنگام ثبت')),
                ('room_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='دمای اتاق')),
                ('ecg_location', models.CharField(blank=True, max_length=100, verbose_name='محل انجام نوار')),
                ('ecg_quality', models.CharField(blank=True, choices=[('good', 'خوب'), ('noisy', 'نویزدار'), ('incomplete', 'ناقص')], max_length=20, verbose_name='کیفیت نوار')),
                ('tech_issue', models.BooleanField(default=False, verbose_name='آیا مشکل تکنیکی وجود داشت؟')),
                ('issue_desc', models.TextField(blank=True, null=True, verbose_name='توضیح مشکل (در صورت وجود)')),
                ('device_serial', models.CharField(blank=True, max_length=100, verbose_name='شماره سریال دستگاه ECG')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('hr', models.PositiveIntegerField(blank=True, null=True, verbose_name='HR (ضربان)')),
                ('rhythm', models.CharField(blank=True, max_length=100, verbose_name='ریتم غالب')),
                ('axis', models.CharField(blank=True, max_length=50, verbose_name='محور قلب (Axis)')),
                ('qrs', models.CharField(blank=True, max_length=50, verbose_name='QRS')),
                ('qtc', models.CharField(blank=True, max_length=50, verbose_name='QTc')),
                ('p_wave', models.CharField(blank=True, max_length=50, verbose_name='P موج')),
                ('st_t', models.CharField(blank=True, max_length=100, verbose_name='ST-T تغییرات')),
                ('q_wave', models.BooleanField(default=False, verbose_name='Q موج پاتولوژیک؟')),
                ('u_wave', models.BooleanField(default=False, verbose_name='U موج مشاهده شد؟')),
                ('tech_opinion', models.TextField(blank=True, verbose_name='توضیح تکنسین')),
                ('ecg_file', models.FileField(blank=True, null=True, upload_to='ecg_files/', verbose_name='فایل نوار قلب')),
                ('ecg_repeat', models.BooleanField(default=False, verbose_name='نیاز به تکرار نوار؟')),
                ('repeat_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='دلیل تکرار')),
                ('tech_signature', models.CharField(blank=True, max_length=100, verbose_name='امضای تکنسین')),
                ('doctor_signature', models.CharField(blank=True, max_length=100, verbose_name='تأیید پزشک ناظر')),
                ('ai_result', models.TextField(blank=True, verbose_name='نتیجه تحلیل سیستم هوشمند')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'نوار قلب (ECG)',
                'verbose_name_plural': 'نوارهای قلب',
                'ordering': ['-created_at'],
            },
        ),
    ]
