# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecg', '0001_initial'),
        ('patient', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_records', to='patient.patient', verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecg_records', to='prescriptions.prescription', verbose_name='نسخه مربوطه'),
        ),
    ]
