# Generated by Django 4.2 on 2025-07-27 10:54

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام مستعار')),
                ('national_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد ملی')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profile/', verbose_name='تصویر پروفایل')),
                ('service_level', models.CharField(choices=[('normal', 'عمومی'), ('cip', 'CIP - خدمات ویژه'), ('vip', 'VIP - بیمار خاص'), ('referral', 'ارجاعی'), ('special', 'خدمات خاص / خیرین')], default='normal', max_length=20, verbose_name='سطح کاربر')),
                ('marriage', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل'), ('other', 'سایر')], max_length=20, null=True, verbose_name='وضعیت تأهل')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], default='fa', max_length=10, verbose_name='زبان')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملیت')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده توسط ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='موبایل تأیید شده')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تأیید شده')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تغییر رمز')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('code', models.SlugField(help_text='مثال: view_user، edit_staff، delete_report', unique=True, verbose_name='کد دسترسی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('verify', 'تأیید شماره'), ('login', 'ورود بدون رمز'), ('reset', 'بازیابی رمز'), ('2fa', 'ورود دو مرحله\u200cای')], max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('label', models.CharField(choices=[('mobile', 'موبایل'), ('home', 'منزل'), ('office', 'دفتر'), ('other', 'سایر')], default='mobile', max_length=20, verbose_name='نوع شماره')),
                ('is_primary', models.BooleanField(default=False, verbose_name='شماره اصلی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='home', max_length=50, verbose_name='برچسب')),
                ('state', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('street', models.TextField(verbose_name='خیابان')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض ارسال')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض مالی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نقش')),
                ('code', models.SlugField(help_text='مثال: admin, doctor, staff', unique=True, verbose_name='کد نقش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.accesspermission', verbose_name='دسترسی\u200cهای این نقش')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
