# Generated by Django 5.2.4 on 2025-07-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان شیفت')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان شغلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'عنوان شغلی',
                'verbose_name_plural': 'عناوین شغلی',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='شماره قرارداد')),
                ('contract_start', models.DateField(verbose_name='تاریخ شروع همکاری')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='staffs/contracts/', verbose_name='فایل قرارداد')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='حقوق پایه ماهانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت منابع انسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staffs', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='staffs.staffposition', verbose_name='عنوان شغلی')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('daily', 'مرخصی روزانه'), ('hourly', 'مرخصی ساعتی')], max_length=10, verbose_name='نوع مرخصی')),
                ('reason', models.TextField(verbose_name='دلیل مرخصی')),
                ('start_date', models.DateField(verbose_name='از تاریخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='از ساعت')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='تا ساعت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='staffs.staff', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'درخواست مرخصی',
                'verbose_name_plural': 'درخواست\u200cهای مرخصی',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_late', models.BooleanField(default=False, verbose_name='تاخیر داشته؟')),
                ('left_early', models.BooleanField(default=False, verbose_name='زودتر خارج شده؟')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ساعت اضافه کاری')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ساعات کارکرد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffs.shift', verbose_name='شیفت')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='staffs.staff', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'لاگ کاری روزانه',
                'verbose_name_plural': 'لاگ\u200cهای کاری روزانه',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تخصیص\u200cدهنده')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staffs.shift', verbose_name='شیفت')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='staffs.staff', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'تخصیص شیفت',
                'verbose_name_plural': 'شیفت\u200cهای تخصیص یافته',
                'unique_together': {('staff', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='ساعت ورود')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('method', models.CharField(choices=[('manual', 'ثبت دستی'), ('finger', 'اثر انگشت'), ('card', 'کارت\u200cخوان'), ('device', 'دستگاه حضور و غیاب')], default='manual', max_length=20, verbose_name='روش ثبت')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت شده در')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staffs.staff', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'حضور / غیاب',
                'verbose_name_plural': 'سوابق حضور / غیاب',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
