# Generated by Django 5.2.4 on 2025-07-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolterHRInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tracking_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد پیگیری')),
                ('install_datetime', models.DateTimeField(verbose_name='زمان و تاریخ نصب')),
                ('patient_education_given', models.BooleanField(default=False, verbose_name='آموزش به بیمار داده شده؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای زمان نصب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hr_holter_installations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='دستگاه هلتر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_holter_installations', to='patient.patient', verbose_name='بیمار')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_holter_installations_done', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین نصب')),
            ],
            options={
                'verbose_name': 'نصب هلتر ضربان',
                'verbose_name_plural': 'نصب\u200cهای هلتر ضربان',
                'ordering': ['-install_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HolterHRReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_datetime', models.DateTimeField(verbose_name='زمان و تاریخ خواندن')),
                ('avg_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='میانگین ضربان قلب')),
                ('min_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='کمترین ضربان قلب')),
                ('min_hr_time', models.TimeField(blank=True, null=True, verbose_name='زمان کمترین ضربان')),
                ('max_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='بیشترین ضربان قلب')),
                ('max_hr_time', models.TimeField(blank=True, null=True, verbose_name='زمان بیشترین ضربان')),
                ('sdnn', models.FloatField(blank=True, null=True, verbose_name='SDNN')),
                ('rmssd', models.FloatField(blank=True, null=True, verbose_name='RMSSD')),
                ('pnn50', models.FloatField(blank=True, null=True, verbose_name='pNN50')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه خوانش')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='holter_reports/hr/', verbose_name='فایل گزارش نهایی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت خوانش')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='holter_hr.holterhrinstallation', verbose_name='رکورد نصب')),
                ('interpreted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تحلیل\u200cگر')),
            ],
            options={
                'verbose_name': 'خواندن هلتر ضربان',
                'verbose_name_plural': 'خوانش\u200cهای هلتر ضربان',
                'ordering': ['-read_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HolterHRReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_datetime', models.DateTimeField(verbose_name='زمان و تاریخ دریافت')),
                ('device_condition_on_return', models.TextField(blank=True, null=True, verbose_name='وضعیت دستگاه در بازگشت')),
                ('patient_feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد بیمار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای دریافت')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception_record', to='holter_hr.holterhrinstallation', verbose_name='رکورد نصب')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'دریافت هلتر ضربان',
                'verbose_name_plural': 'دریافت\u200cهای هلتر ضربان',
                'ordering': ['-receive_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='holterhrinstallation',
            index=models.Index(fields=['install_datetime'], name='holter_hr_h_install_760887_idx'),
        ),
        migrations.AddIndex(
            model_name='holterhrinstallation',
            index=models.Index(fields=['tracking_code'], name='holter_hr_h_trackin_7dba3d_idx'),
        ),
        migrations.AddIndex(
            model_name='holterhrinstallation',
            index=models.Index(fields=['patient'], name='holter_hr_h_patient_f19611_idx'),
        ),
        migrations.AddIndex(
            model_name='holterhrreading',
            index=models.Index(fields=['read_datetime'], name='holter_hr_h_read_da_ee3cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='holterhrreading',
            index=models.Index(fields=['installation'], name='holter_hr_h_install_0738d3_idx'),
        ),
        migrations.AddIndex(
            model_name='holterhrreception',
            index=models.Index(fields=['receive_datetime'], name='holter_hr_h_receive_d8291e_idx'),
        ),
        migrations.AddIndex(
            model_name='holterhrreception',
            index=models.Index(fields=['installation'], name='holter_hr_h_install_31d80c_idx'),
        ),
    ]
