# Generated by Django 4.2 on 2025-07-28 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='نقشی که مسئول رسیدگی به این خدمت است و اعلان مربوطه را دریافت می\u200cکند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_types', to='accounts.role', verbose_name='نقش مسئول خدمت'),
        ),
    ]
