# Generated by Django 5.2.4 on 2025-07-27 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('exam_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انجام تست')),
                ('stress_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع تست (ورزشی یا اکو)')),
                ('protocol', models.CharField(blank=True, max_length=100, null=True, verbose_name='پروتکل تست')),
                ('stress_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت تست (دقیقه)')),
                ('test_duration', models.DurationField(blank=True, null=True, verbose_name='مدت تست (فرمت زمان)')),
                ('stress_start_time', models.TimeField(blank=True, null=True, verbose_name='زمان شروع تست')),
                ('stress_stop_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='علت توقف تست')),
                ('stress_conditions', models.TextField(blank=True, null=True, verbose_name='شرایط حین تست')),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن بیمار')),
                ('mets', models.FloatField(blank=True, null=True, verbose_name='METs')),
                ('hr_rest', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ضربان قلب در استراحت')),
                ('hr_peak', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ضربان قلب در اوج')),
                ('hr_peak_metric', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ضربان اوج (متریک)')),
                ('max_hr', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر HR')),
                ('target_hr', models.PositiveIntegerField(blank=True, null=True, verbose_name='هدف HR')),
                ('sbp_rest', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فشار سیستولیک در استراحت')),
                ('sbp_peak', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فشار سیستولیک در اوج')),
                ('sbp_peak_metric', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فشار اوج (متریک)')),
                ('bp_during_test', models.CharField(blank=True, max_length=50, null=True, verbose_name='فشار خون حین تست')),
                ('recovery_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت ریکاوری')),
                ('hr_recovery', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ضربان قلب در ریکاوری')),
                ('sbp_recovery', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فشار سیستولیک در ریکاوری')),
                ('recovery_st_change', models.CharField(blank=True, max_length=50, null=True, verbose_name='تغییرات ST در ریکاوری')),
                ('recovery_symptoms', models.JSONField(blank=True, null=True, verbose_name='علائم در ریکاوری')),
                ('recovery_monitoring', models.TextField(blank=True, null=True, verbose_name='پایش در ریکاوری')),
                ('pretest_medications', models.CharField(blank=True, max_length=100, null=True, verbose_name='داروهای قبل از تست')),
                ('baseline_ecg', models.CharField(blank=True, max_length=100, null=True, verbose_name='ECG پایه')),
                ('pretest_sbp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فشار سیستولیک قبل از تست')),
                ('pretest_dbp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فشار دیاستولیک قبل از تست')),
                ('pretest_contra', models.CharField(blank=True, max_length=100, null=True, verbose_name='موارد منع قبل از تست')),
                ('symptoms', models.JSONField(blank=True, null=True, verbose_name='علائم حین تست')),
                ('stress_symptomatic', models.CharField(blank=True, max_length=50, null=True, verbose_name='تست علامت\u200cدار')),
                ('borg_scale', models.CharField(blank=True, max_length=10, null=True, verbose_name='مقیاس بورگ')),
                ('test_result', models.CharField(blank=True, max_length=200, null=True, verbose_name='نتیجه تست')),
                ('arrhythmia_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع آریتمی')),
                ('ecg_leads', models.CharField(blank=True, max_length=100, null=True, verbose_name='لیدهای ECG')),
                ('ecg_changes', models.TextField(blank=True, null=True, verbose_name='تغییرات ECG')),
                ('wall_motion_abnormalities', models.BooleanField(default=False, verbose_name='اختلال حرکتی دیواره؟')),
                ('ischemic_changes', models.BooleanField(default=False, verbose_name='تغییرات ایسکمیک؟')),
                ('arrhythmia_occurred', models.BooleanField(default=False, verbose_name='آریتمی در حین تست؟')),
                ('rwma_severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شدت RWMA')),
                ('ef_rest', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='EF در استراحت')),
                ('ef_post', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='EF پس از تست')),
                ('mr_grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='درجه MR')),
                ('rwma_walls', models.TextField(blank=True, null=True, verbose_name='دیواره\u200cهای درگیر RWMA')),
                ('stress_video', models.FileField(blank=True, null=True, upload_to='stress_test/videos/', verbose_name='ویدیوی تست')),
                ('echo_file', models.FileField(blank=True, null=True, upload_to='echo/stress/', verbose_name='فایل تست اکو')),
                ('image_saved', models.CharField(blank=True, max_length=10, null=True, verbose_name='تصاویر ذخیره شده')),
                ('technical_issues', models.TextField(blank=True, null=True, verbose_name='مشکلات فنی')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='یافته\u200cها')),
                ('doctor_opinion', models.TextField(blank=True, null=True, verbose_name='نظر پزشک')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='توصیه بعد از تست')),
                ('final_comment', models.TextField(blank=True, null=True, verbose_name='توضیح نهایی')),
                ('final_diagnosis', models.CharField(blank=True, max_length=50, null=True, verbose_name='تشخیص نهایی')),
                ('final_plan', models.CharField(blank=True, max_length=200, null=True, verbose_name='برنامه نهایی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_tests', to='patient.patient', verbose_name='بیمار')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_tests', to='prescriptions.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'تست ورزش / استرس اکو',
                'verbose_name_plural': 'گزارش\u200cهای تست ورزش / استرس اکو',
                'ordering': ['-created_at'],
            },
        ),
    ]
