# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('symptom_onset', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع علائم')),
                ('angiography_result', models.TextField(blank=True, null=True, verbose_name='نتیجه آنژیوگرافی')),
                ('followup_plan', models.TextField(blank=True, null=True, verbose_name='توصیه به پیگیری')),
                ('referral_specialist', models.CharField(blank=True, choices=[('none', 'ندارد'), ('neurology', 'نورولوژی'), ('electrophysiology', 'ریتمولوژی'), ('general_surgery', 'جراحی عمومی')], max_length=50, null=True, verbose_name='ارجاع به تخصص دیگر')),
                ('final_doctor_note', models.TextField(blank=True, null=True, verbose_name='نظر نهایی پزشک')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='doctors.doctor', verbose_name='پزشک معالج')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.patient')),
            ],
            options={
                'verbose_name': 'نسخه پزشک',
                'verbose_name_plural': 'نسخه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع دستگاه')),
                ('battery_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درصد باتری')),
                ('device_implant_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نصب')),
                ('shock_occurred', models.BooleanField(blank=True, null=True, verbose_name='شوک ثبت شده؟')),
                ('lead_problem', models.BooleanField(blank=True, null=True, verbose_name='لید دارای مشکل؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت پزشک درباره دستگاه')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_assessment', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'ارزیابی دستگاه قلبی',
                'verbose_name_plural': 'ارزیابی\u200cهای دستگاه قلبی',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dose', models.CharField(max_length=50, verbose_name='دوز')),
                ('total', models.PositiveIntegerField(verbose_name='تعداد کل')),
                ('per_day', models.PositiveIntegerField(verbose_name='مصرف روزانه')),
                ('med_type', models.CharField(choices=[('oral', 'خوراکی'), ('injectable', 'تزریقی'), ('sublingual', 'زیر زبانی')], max_length=30, verbose_name='نوع مصرف')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'داروی نسخه',
                'verbose_name_plural': 'داروهای نسخه',
            },
        ),
        migrations.CreateModel(
            name='SurgeryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need_battery_replacement', models.BooleanField(blank=True, null=True, verbose_name='نیاز به تعویض باتری؟')),
                ('need_lead_revision', models.BooleanField(blank=True, null=True, verbose_name='نیاز به اصلاح یا تعویض لید؟')),
                ('need_device_extraction', models.BooleanField(blank=True, null=True, verbose_name='نیاز به استخراج دستگاه؟')),
                ('general_surgery_needed', models.BooleanField(blank=True, null=True, verbose_name='نیاز به جراحی عمومی دیگر؟')),
                ('general_surgery_reason', models.TextField(blank=True, null=True, verbose_name='توضیح درباره جراحی عمومی')),
                ('suggested_surgery_type', models.CharField(blank=True, choices=[('battery_change', 'تعویض باتری'), ('lead_revision', 'تعویض لید'), ('extraction', 'خارج\u200cسازی'), ('reimplant', 'کاشت مجدد'), ('exploration', 'بررسی تخصصی بیشتر'), ('general', 'جراحی عمومی')], max_length=100, null=True, verbose_name='نوع جراحی پیشنهادی')),
                ('suggested_surgery_note', models.TextField(blank=True, null=True, verbose_name='توضیحات جراحی')),
                ('implant_location', models.CharField(blank=True, choices=[('left_submuscular', 'زیر عضله چپ'), ('right_subcutaneous', 'زیر جلد راست'), ('previous_site', 'محل قبلی'), ('other', 'سایر')], max_length=100, null=True, verbose_name='محل پیشنهادی نصب')),
                ('implant_location_note', models.TextField(blank=True, null=True, verbose_name='توضیحات محل نصب')),
                ('preferred_surgery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیشنهادی')),
                ('surgery_center', models.CharField(blank=True, max_length=150, null=True, verbose_name='مرکز جراحی ارجاعی')),
                ('surgeon_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام جراح')),
                ('doctor_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت نهایی پزشک')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_plan', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'برنامه جراحی',
                'verbose_name_plural': 'برنامه\u200cهای جراحی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holter_ecg', models.CharField(choices=[('needed', 'نیاز هست'), ('done', 'انجام شده'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('holter_bp', models.CharField(choices=[('needed', 'نیاز هست'), ('done', 'انجام شده'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('tilt_test', models.CharField(choices=[('needed', 'نیاز هست'), ('done', 'انجام شده'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('stress_test', models.CharField(choices=[('needed', 'نیاز هست'), ('done', 'انجام شده'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('echo', models.CharField(choices=[('needed', 'نیاز هست'), ('done', 'انجام شده'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('tee', models.CharField(choices=[('needed', 'نیاز هست'), ('done', 'انجام شده'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='اکو مری')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_request', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'درخواست تست',
                'verbose_name_plural': 'درخواست\u200cهای تست',
            },
        ),
    ]
