# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=100, verbose_name='نام حساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('balance', models.BigIntegerField(default=0, verbose_name='مانده حساب (ریال)')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='شرح آیتم')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='تعداد/مقدار')),
                ('unit_price', models.BigIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.BigIntegerField(editable=False, verbose_name='جمع کل (ریال)')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.BigIntegerField(default=0, verbose_name='بدهکار (ریال)')),
                ('credit', models.BigIntegerField(default=0, verbose_name='بستانکار (ریال)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ثبت دفتر کل',
                'verbose_name_plural': 'ثبت\u200cهای دفتر کل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (ریال)')),
                ('transaction_type', models.CharField(choices=[('inflow', 'ورودی'), ('outflow', 'خروجی')], max_length=10, verbose_name='نوع تراکنش')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('online', 'پرداخت آنلاین'), ('insurance', 'بیمه'), ('combined', 'ترکیبی'), ('other', 'سایر')], max_length=20, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transactions/bank_receipts/', verbose_name='فایل رسید')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='accounting/documents/', verbose_name='فایل')),
                ('doc_type', models.CharField(max_length=50, verbose_name='نوع فایل (مثلاً: رسید، قرارداد، …)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='شماره فاکتور')),
                ('discount', models.BigIntegerField(default=0, verbose_name='تخفیف (ریال)')),
                ('tax', models.BigIntegerField(default=0, verbose_name='مالیات (ریال)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('open', 'باز'), ('paid', 'پرداخت شده'), ('void', 'باطل شده'), ('uncollectible', 'غیرقابل وصول')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجادکننده')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
