# Generated by Django 5.2.4 on 2025-07-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolterBPInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tracking_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='کد پیگیری')),
                ('install_datetime', models.DateTimeField(verbose_name='زمان و تاریخ نصب')),
                ('patient_education_given', models.BooleanField(default=False, verbose_name='آموزش به بیمار داده شده؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای زمان نصب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bp_holter_installations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='دستگاه هلتر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bp_holter_installations', to='patient.patient', verbose_name='بیمار')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bp_holter_installations_done', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین نصب')),
            ],
            options={
                'verbose_name': 'نصب هلتر فشار',
                'verbose_name_plural': 'نصب\u200cهای هلتر فشار',
                'ordering': ['-install_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HolterBPReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_datetime', models.DateTimeField(verbose_name='زمان و تاریخ خواندن')),
                ('avg_systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='میانگین فشار سیستولیک')),
                ('min_systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='کمترین فشار سیستولیک')),
                ('min_systolic_time', models.TimeField(blank=True, null=True, verbose_name='زمان کمترین فشار سیستولیک')),
                ('max_systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='بیشترین فشار سیستولیک')),
                ('max_systolic_time', models.TimeField(blank=True, null=True, verbose_name='زمان بیشترین فشار سیستولیک')),
                ('avg_diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='میانگین فشار دیاستولیک')),
                ('min_diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='کمترین فشار دیاستولیک')),
                ('min_diastolic_time', models.TimeField(blank=True, null=True, verbose_name='زمان کمترین فشار دیاستولیک')),
                ('max_diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='بیشترین فشار دیاستولیک')),
                ('max_diastolic_time', models.TimeField(blank=True, null=True, verbose_name='زمان بیشترین فشار دیاستولیک')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه خوانش')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='holter_reports/bp/', verbose_name='فایل گزارش نهایی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت خوانش')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='holter_bp.holterbpinstallation', verbose_name='رکورد نصب')),
                ('interpreted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تحلیل\u200cگر')),
            ],
            options={
                'verbose_name': 'خواندن هلتر فشار',
                'verbose_name_plural': 'خوانش\u200cهای هلتر فشار',
                'ordering': ['-read_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HolterBPReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_datetime', models.DateTimeField(verbose_name='زمان و تاریخ دریافت')),
                ('device_condition_on_return', models.TextField(blank=True, null=True, verbose_name='وضعیت دستگاه در بازگشت')),
                ('patient_feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد بیمار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای دریافت')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception_record', to='holter_bp.holterbpinstallation', verbose_name='رکورد نصب')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'دریافت هلتر فشار',
                'verbose_name_plural': 'دریافت\u200cهای هلتر فشار',
                'ordering': ['-receive_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='holterbpinstallation',
            index=models.Index(fields=['install_datetime'], name='holter_bp_h_install_40c87f_idx'),
        ),
        migrations.AddIndex(
            model_name='holterbpinstallation',
            index=models.Index(fields=['tracking_code'], name='holter_bp_h_trackin_ac73c3_idx'),
        ),
        migrations.AddIndex(
            model_name='holterbpinstallation',
            index=models.Index(fields=['patient'], name='holter_bp_h_patient_6e4d05_idx'),
        ),
        migrations.AddIndex(
            model_name='holterbpreading',
            index=models.Index(fields=['read_datetime'], name='holter_bp_h_read_da_dfce06_idx'),
        ),
        migrations.AddIndex(
            model_name='holterbpreading',
            index=models.Index(fields=['installation'], name='holter_bp_h_install_4a20ae_idx'),
        ),
        migrations.AddIndex(
            model_name='holterbpreception',
            index=models.Index(fields=['receive_datetime'], name='holter_bp_h_receive_0d91e2_idx'),
        ),
        migrations.AddIndex(
            model_name='holterbpreception',
            index=models.Index(fields=['installation'], name='holter_bp_h_install_2a5b36_idx'),
        ),
    ]
