# Generated by Django 5.2.4 on 2025-07-27 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiltTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('referring_physician', models.CharField(blank=True, max_length=100, null=True, verbose_name='پزشک ارجاع\u200cدهنده')),
                ('referral_reason', models.TextField(blank=True, null=True, verbose_name='علت ارجاع')),
                ('prior_symptoms', models.CharField(blank=True, max_length=50, null=True, verbose_name='علائم قبلی')),
                ('last_event_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین حمله')),
                ('had_syncope', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], max_length=10, null=True, verbose_name='آیا سنکوپ رخ داد؟')),
                ('hr_during_syncope', models.PositiveIntegerField(blank=True, null=True, verbose_name='HR حین سنکوپ')),
                ('bp_drop', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], max_length=10, null=True, verbose_name='فشار خون افت کرد؟')),
                ('symptom_onset_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان بروز علائم (دقیقه)')),
                ('standing_symptoms', models.JSONField(blank=True, null=True, verbose_name='علائم حین ایستادن')),
                ('recovery_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان بازیابی (دقیقه)')),
                ('response_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع پاسخ نهایی')),
                ('final_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='یافته نهایی پزشک')),
                ('tilt_upload', models.FileField(blank=True, null=True, upload_to='tilt_tests/', verbose_name='آپلود فایل تصویری یا گزارش')),
                ('doctor_comment', models.TextField(blank=True, null=True, verbose_name='توضیح پزشک')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tilt_tests', to='prescriptions.prescription', verbose_name='نسخه مرتبط')),
            ],
            options={
                'verbose_name': 'گزارش تست تیلت',
                'verbose_name_plural': 'گزارش\u200cهای تست تیلت',
                'ordering': ['-created_at'],
            },
        ),
    ]
