# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('type', models.CharField(choices=[('supplier', 'تأمین\u200cکننده'), ('warranty', 'گارانتی\u200cدهنده'), ('maintenance', 'شرکت نگهداری'), ('calibration', 'مرکز کالیبراسیون')], max_length=20, verbose_name='نوع')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص تماس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('drug', 'دارو'), ('consumable', 'مصرفی'), ('equipment', 'تجهیزات پزشکی'), ('capital', 'سرمایه\u200cای'), ('loanable', 'قابل امانت')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('unit', models.CharField(default='واحد', max_length=50, verbose_name='واحد شمارش')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='سازنده')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره سریال')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='بارکد')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('warranty_start', models.DateField(blank=True, null=True, verbose_name='شروع گارانتی')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='پایان گارانتی')),
                ('warranty_document', models.FileField(blank=True, null=True, upload_to='warranties/', verbose_name='فایل گارانتی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('in_use', 'در حال استفاده'), ('in_repair', 'در حال تعمیر'), ('damaged', 'خراب\u200cشده'), ('lost', 'مفقودی'), ('decommissioned', 'از رده خارج'), ('with_patient', 'در اختیار بیمار')], default='active', max_length=20, verbose_name='وضعیت فعلی')),
                ('is_consumable', models.BooleanField(default=False, verbose_name='مصرفی است؟')),
                ('is_loanable', models.BooleanField(default=False, verbose_name='امکان امانت دارد؟')),
                ('is_decommissioned', models.BooleanField(default=False, verbose_name='از رده خارج شده؟')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل نگهداری فعلی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='inventory.partner', verbose_name='تأمین\u200cکننده')),
                ('warranty_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_items', to='inventory.partner', verbose_name='شرکت گارانتی\u200cدهنده')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='فایل')),
                ('doc_type', models.CharField(choices=[('manual', 'دفترچه راهنما'), ('repair_report', 'گزارش تعمیر'), ('calibration_certificate', 'گواهی کالیبراسیون'), ('warranty', 'سند گارانتی'), ('other', 'سایر')], max_length=50, verbose_name='نوع فایل')),
                ('uploaded_by', models.CharField(max_length=255, verbose_name='آپلودکننده')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.item', verbose_name='تجهیز')),
            ],
        ),
        migrations.CreateModel(
            name='DecommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ اسقاط')),
                ('reason', models.TextField(verbose_name='علت اسقاط')),
                ('confirmed_by', models.CharField(max_length=255, verbose_name='تأییدکننده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255, verbose_name='از محل')),
                ('to_location', models.CharField(max_length=255, verbose_name='به محل')),
                ('moved_by', models.CharField(max_length=255, verbose_name='کاربر جابجاکننده')),
                ('move_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ جابجایی')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='هدف جابجایی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('in_use', 'در حال استفاده'), ('in_repair', 'در حال تعمیر'), ('damaged', 'خراب\u200cشده'), ('lost', 'مفقودی'), ('decommissioned', 'از رده خارج'), ('with_patient', 'در اختیار بیمار')], max_length=20, verbose_name='وضعیت جدید')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('changed_by', models.CharField(max_length=255, verbose_name='کاربر تغییردهنده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255, verbose_name='نام بیمار')),
                ('external_patient_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد بیمار (اختیاری)')),
                ('loan_date', models.DateField(verbose_name='تاریخ امانت')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت مورد انتظار')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت واقعی')),
                ('status', models.CharField(choices=[('loaned', 'در امانت'), ('returned', 'بازگشته'), ('damaged', 'خراب\u200cشده'), ('lost', 'مفقودی')], default='loaned', max_length=20, verbose_name='وضعیت')),
                ('staff', models.CharField(max_length=255, verbose_name='مسئول ثبت / تحویل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
            ],
            options={
                'verbose_name': 'امانت تجهیز',
                'verbose_name_plural': 'امانت\u200cهای تجهیزات',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(verbose_name='تاریخ گزارش خرابی')),
                ('maintenance_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انجام تعمیر')),
                ('issue_description', models.TextField(verbose_name='شرح خرابی')),
                ('maintenance_action', models.TextField(blank=True, null=True, verbose_name='اقدام انجام\u200cشده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('repaired', 'تعمیر شده'), ('replaced', 'تعویض شده'), ('irreparable', 'غیرقابل تعمیر')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='هزینه (تومان)')),
                ('technician', models.CharField(blank=True, max_length=255, null=True, verbose_name='تکنسین')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partner', verbose_name='شرکت تعمیرکار')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(verbose_name='تاریخ کالیبراسیون')),
                ('expiration_date', models.DateField(verbose_name='تاریخ انقضای کالیبراسیون')),
                ('calibration_certificate', models.FileField(blank=True, null=True, upload_to='calibrations/', verbose_name='گواهی کالیبراسیون')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partner', verbose_name='شرکت کالیبراسیون')),
            ],
        ),
        migrations.CreateModel(
            name='PatientUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255, verbose_name='نام بیمار')),
                ('external_patient_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد بیمار (اختیاری)')),
                ('date', models.DateField(verbose_name='تاریخ استفاده')),
                ('performed_by', models.CharField(max_length=255, verbose_name='کاربر / پرسنل انجام\u200cدهنده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(verbose_name='دوره (روز)')),
                ('next_due_date', models.DateField(verbose_name='تاریخ سررسید بعدی')),
                ('assigned_to', models.CharField(max_length=255, verbose_name='مسئول انجام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام\u200cشده'), ('overdue', 'به تعویق افتاده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ورود')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره فاکتور')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partner', verbose_name='تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'ورود به انبار',
                'verbose_name_plural': 'ورودهای انبار',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بچ')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='کالا')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockin', verbose_name='رسید ورود')),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ خروج')),
                ('department', models.CharField(max_length=100, verbose_name='واحد مقصد')),
                ('staff', models.CharField(max_length=100, verbose_name='تحویل\u200cگیرنده / مسئول')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='هدف یا توضیح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'خروج از انبار',
                'verbose_name_plural': 'خروج\u200cهای انبار',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='کالا')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockout', verbose_name='سند خروج')),
            ],
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('return_loan', 'بازگشت امانت از بیمار'), ('maintenance', 'نگهداری دوره\u200cای'), ('calibration', 'کالیبراسیون دوره\u200cای'), ('low_stock', 'هشدار کمبود موجودی'), ('other', 'سایر')], max_length=50, verbose_name='نوع وظیفه')),
                ('assigned_to', models.CharField(max_length=255, verbose_name='واگذار شده به')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'انجام شده'), ('overdue', 'به تعویق افتاده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='ایجادشده توسط سیستم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='تجهیز مرتبط')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('location', models.CharField(max_length=255, verbose_name='محل نگهداری')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بچ / سری ساخت')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('min_required', models.PositiveIntegerField(default=0, verbose_name='حداقل موجودی لازم')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'موجودی کالا',
                'verbose_name_plural': 'موجودی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('item', 'batch_number', 'location')},
            },
        ),
    ]
