# Generated by Django 5.2.4 on 2025-07-27 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTEEchoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انجام')),
                ('ef', models.CharField(blank=True, max_length=50, null=True, verbose_name='کسر تخلیه (EF)')),
                ('lv_dysfunction', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اختلال عملکرد بطن چپ')),
                ('lvedd', models.CharField(blank=True, max_length=50, null=True, verbose_name='قطر پایانی دیاستول بطن چپ (LVEDD)')),
                ('lvesd', models.CharField(blank=True, max_length=50, null=True, verbose_name='قطر پایانی سیستول بطن چپ (LVESD)')),
                ('gls', models.CharField(blank=True, max_length=50, null=True, verbose_name='کرنش طولی جهانی (GLS)')),
                ('image_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع تصویر')),
                ('tapse', models.CharField(blank=True, max_length=50, null=True, verbose_name='حرکت حلقوی انتهای سیستول بطن راست (TAPSE)')),
                ('spap', models.CharField(blank=True, max_length=50, null=True, verbose_name='فشار سیستولیک شریان ریوی (SPAP)')),
                ('ivc_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت ورید اجوف تحتانی (IVC)')),
                ('mitral_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اختلال دریچه میترال')),
                ('mitral_severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شدت اختلال میترال')),
                ('mitral_features', models.CharField(blank=True, max_length=50, null=True, verbose_name='ویژگی\u200cهای میترال')),
                ('aortic_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اختلال دریچه آئورت')),
                ('aortic_severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شدت اختلال آئورت')),
                ('aortic_features', models.CharField(blank=True, max_length=50, null=True, verbose_name='ویژگی\u200cهای آئورت')),
                ('tricuspid_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اختلال دریچه تری\u200cکاسپید')),
                ('tricuspid_severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شدت اختلال تری\u200cکاسپید')),
                ('pulmonary_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اختلال دریچه ریوی')),
                ('pulmonary_severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='شدت اختلال ریوی')),
                ('pericardial_effusion', models.CharField(blank=True, max_length=50, null=True, verbose_name='مایع پریکارد')),
                ('pleural_effusion', models.CharField(blank=True, max_length=50, null=True, verbose_name='مایع پلور')),
                ('mass_or_clot', models.CharField(blank=True, max_length=50, null=True, verbose_name='توده / لخته / ویژتیشن')),
                ('aneurysm', models.CharField(blank=True, max_length=50, null=True, verbose_name='آنوریسم / دیواره غیرطبیعی')),
                ('image_quality', models.CharField(blank=True, max_length=50, null=True, verbose_name='کیفیت تصویر')),
                ('image_limitation_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='علت ضعف کیفیت تصویر')),
                ('probe_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع پروب / تکنیک')),
                ('ecg_sync', models.CharField(blank=True, max_length=10, null=True, verbose_name='هماهنگی با ECG')),
                ('patient_cooperation', models.CharField(blank=True, max_length=50, null=True, verbose_name='همکاری بیمار')),
                ('all_views_taken', models.CharField(blank=True, max_length=10, null=True, verbose_name='آیا تمام نماها گرفته شد؟')),
                ('technician_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام تکنسین')),
                ('technician_note', models.TextField(blank=True, null=True, verbose_name='توضیحات تکنسین')),
                ('need_advanced_echo', models.CharField(blank=True, max_length=50, null=True, verbose_name='نیاز به اکو تخصصی')),
                ('reason_advanced_echo', models.CharField(blank=True, max_length=100, null=True, verbose_name='علت درخواست اکو تخصصی')),
                ('reporting_physician', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پزشک گزارش\u200cدهنده')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='تاریخ گزارش')),
                ('final_report', models.TextField(blank=True, null=True, verbose_name='تفسیر نهایی پزشک')),
                ('echo_file', models.FileField(blank=True, null=True, upload_to='echo/tte/', verbose_name='فایل اکو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tte_echos', to='patient.patient', verbose_name='بیمار')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tte_echos', to='prescriptions.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'اکوکاردیوگرافی (TTE)',
                'verbose_name_plural': 'گزارش\u200cهای اکوکاردیوگرافی (TTE)',
                'ordering': ['-exam_datetime'],
            },
        ),
    ]
