# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'سابقه امانت دستگاه',
                'verbose_name_plural': 'سوابق امانت',
            },
        ),
        migrations.CreateModel(
            name='HolterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='شماره سریال')),
                ('asset_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره اموال')),
                ('internal_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد داخلی / QR')),
                ('model_name', models.CharField(max_length=100, verbose_name='مدل دستگاه')),
                ('device_type', models.CharField(choices=[('bp', 'فشار خون'), ('hr', 'ضربان قلب'), ('combo', 'فشار + ضربان')], max_length=20, verbose_name='نوع دستگاه')),
                ('status', models.CharField(choices=[('in_clinic', 'در کلینیک'), ('assigned', 'امانت بیمار'), ('ready', 'آماده استفاده'), ('waiting_repair', 'در انتظار تعمیر'), ('repairing', 'در حال تعمیر'), ('broken', 'غیر قابل استفاده')], default='in_clinic', max_length=30, verbose_name='وضعیت')),
                ('assigned_until', models.DateTimeField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('battery_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت باتری')),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسخه نرم\u200cافزار')),
                ('is_calibrated', models.BooleanField(default=True, verbose_name='کالیبره شده؟')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='آخرین سرویس')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='پایان گارانتی')),
                ('health_note', models.TextField(blank=True, null=True, verbose_name='یادداشت فنی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دستگاه هولتر',
                'verbose_name_plural': 'دستگاه\u200cهای هولتر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HolterInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت نصب')),
                ('technician_name', models.CharField(max_length=100, verbose_name='تکنسین')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل نصب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نصب دستگاه',
                'verbose_name_plural': 'نصب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='HolterRepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(verbose_name='شرح مشکل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال تعمیر'), ('done', 'تعمیر شده'), ('discarded', 'غیرفعال/اسقاط شده')], default='pending', max_length=20, verbose_name='وضعیت تعمیر')),
                ('repair_start', models.DateField(verbose_name='تاریخ شروع')),
                ('repair_end', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='هزینه تعمیر (تومان)')),
                ('repaired_by', models.CharField(max_length=100, verbose_name='نام تعمیرکار')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت تکمیلی')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'گزارش تعمیر دستگاه هولتر',
                'verbose_name_plural': 'تعمیرات دستگاه\u200cهای هولتر',
                'ordering': ['-repair_start'],
            },
        ),
        migrations.CreateModel(
            name='HolterStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('in_clinic', 'در کلینیک'), ('assigned', 'امانت بیمار'), ('ready', 'آماده استفاده'), ('waiting_repair', 'در انتظار تعمیر'), ('repairing', 'در حال تعمیر'), ('broken', 'غیر قابل استفاده')], max_length=30)),
                ('new_status', models.CharField(choices=[('in_clinic', 'در کلینیک'), ('assigned', 'امانت بیمار'), ('ready', 'آماده استفاده'), ('waiting_repair', 'در انتظار تعمیر'), ('repairing', 'در حال تعمیر'), ('broken', 'غیر قابل استفاده')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت دستگاه',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت دستگاه',
            },
        ),
    ]
