# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecg', '0001_initial'),
        ('holter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='شماره پرونده')),
                ('total_receptions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل پذیرش\u200cها')),
                ('blood_group', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='گروه خونی')),
                ('has_allergy', models.BooleanField(default=False, verbose_name='آیا آلرژی دارید؟')),
                ('allergy_info', models.TextField(blank=True, verbose_name='توضیحات آلرژی')),
                ('chronic_diseases', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('diabetes', 'دیابت'), ('kidney', 'نارسایی کلیه'), ('cardio', 'بیماری قلبی'), ('respiratory', 'بیماری ریوی'), ('other', 'سایر')], max_length=100, verbose_name='بیماری های مزمن')),
                ('heart_surgery', models.BooleanField(default=False, verbose_name='سابقه جراحی قلبی')),
                ('surgery_description', models.TextField(blank=True, verbose_name='توضیحات جراحی')),
                ('mobility_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('independent', 'مستقل'), ('wheelchair', 'نیازمند ویلچر'), ('bedridden', 'زمین\u200cگیر')], max_length=50, verbose_name='وضعیت توان حرکتی')),
                ('special_needs', models.CharField(blank=True, max_length=100, verbose_name='نیاز به خدمات ویژه')),
                ('health_literacy', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('low', 'پایین'), ('medium', 'متوسط'), ('high', 'بالا')], max_length=20, verbose_name='سواد سلامت')),
                ('blood_sugar_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('normal', 'نرمال'), ('prediabetes', 'پیش\u200cدیابت'), ('diabetes_type1', 'دیابت نوع ۱'), ('diabetes_type2', 'دیابت نوع ۲'), ('gestational', 'دیابت بارداری'), ('unknown', 'نامشخص')], max_length=30, verbose_name='وضعیت قند خون')),
                ('basic_insurance_company', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('tamin', 'تأمین اجتماعی'), ('salamat', 'سلامت'), ('iran', 'بیمه ایران'), ('asia', 'بیمه آسیا'), ('dana', 'بیمه دانا'), ('alborz', 'بیمه البرز'), ('kosar', 'بیمه کوثر'), ('mellat', 'بیمه ملت'), ('sina', 'بیمه سینا'), ('moalem', 'بیمه معلم'), ('novin', 'بیمه نوین'), ('pasargad', 'بیمه پاسارگاد'), ('other', 'سایر')], max_length=50, verbose_name='شرکت بیمه پایه')),
                ('basic_insurance_number', models.CharField(blank=True, max_length=20, verbose_name='شماره بیمه پایه')),
                ('basic_insurance_file', models.FileField(blank=True, null=True, upload_to='insurance/basic/', verbose_name='کارت بیمه پایه')),
                ('supplementary_insurance_company', models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('tamin', 'تأمین اجتماعی'), ('salamat', 'سلامت'), ('iran', 'بیمه ایران'), ('asia', 'بیمه آسیا'), ('dana', 'بیمه دانا'), ('alborz', 'بیمه البرز'), ('kosar', 'بیمه کوثر'), ('mellat', 'بیمه ملت'), ('sina', 'بیمه سینا'), ('moalem', 'بیمه معلم'), ('novin', 'بیمه نوین'), ('pasargad', 'بیمه پاسارگاد'), ('other', 'سایر')], max_length=50, verbose_name='شرکت بیمه تکمیلی')),
                ('supplementary_insurance_number', models.CharField(blank=True, max_length=20, verbose_name='شماره بیمه تکمیلی')),
                ('supplementary_insurance_file', models.FileField(blank=True, null=True, upload_to='insurance/supplementary/', verbose_name='کارت بیمه تکمیلی')),
                ('is_referred', models.BooleanField(default=False, verbose_name='بیمه ارجاعی است؟')),
                ('referring_doctor', models.CharField(blank=True, max_length=100, verbose_name='پزشک ارجاع دهنده')),
                ('referring_center', models.CharField(blank=True, max_length=100, verbose_name='مرکز ارجاع')),
                ('referral_file', models.FileField(blank=True, null=True, upload_to='referrals/', verbose_name='فایل ارجاع')),
                ('companion_name', models.CharField(blank=True, max_length=100, verbose_name='نام همراه')),
                ('companion_relation', models.CharField(blank=True, max_length=50, verbose_name='نسبت همراه')),
                ('companion_phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس همراه')),
                ('companion_decision', models.BooleanField(default=False, verbose_name='اجازه تصمیم گیری دارد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='patient_files/', verbose_name='فایل پزشکی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('ecg', 'نوار قلب'), ('holter', 'هولتر'), ('lab', 'آزمایش'), ('imaging', 'تصویربرداری'), ('other', 'سایر')], max_length=50, verbose_name='نوع فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patient.patient', verbose_name='بیمار')),
                ('related_ecg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_files', to='ecg.ecgrecord', verbose_name='مرتبط با نوار قلب')),
                ('related_holter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_files', to='holter.holterdevice', verbose_name='مرتبط با هولتر')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'فایل پزشکی',
                'verbose_name_plural': 'فایل\u200cهای پزشکی بیمار',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
