# Generated by Django 5.2.4 on 2025-07-27 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TEEEchoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انجام')),
                ('sedation_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع آرام\u200cبخش')),
                ('patient_cooperation', models.CharField(blank=True, choices=[('good', 'خوب'), ('moderate', 'متوسط'), ('poor', 'ضعیف')], max_length=50, null=True, verbose_name='میزان همکاری بیمار')),
                ('visualization_quality', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('acceptable', 'قابل قبول'), ('poor', 'ضعیف')], max_length=50, null=True, verbose_name='کیفیت تصاویر')),
                ('la_appendage_status', models.TextField(blank=True, null=True, verbose_name='وضعیت LAA')),
                ('interatrial_septum', models.TextField(blank=True, null=True, verbose_name='سپتوم بین دهلیزی')),
                ('valvular_findings', models.TextField(blank=True, null=True, verbose_name='مشاهدات مربوط به دریچه\u200cها')),
                ('presence_of_clot', models.BooleanField(default=False, verbose_name='وجود لخته؟')),
                ('pericardial_effusion', models.BooleanField(default=False, verbose_name='افیوژن پریکارد؟')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='یافته\u200cها')),
                ('doctor_opinion', models.TextField(blank=True, null=True, verbose_name='نظر پزشک')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='توصیه')),
                ('echo_file', models.FileField(blank=True, null=True, upload_to='echo/tee/', verbose_name='فایل پیوست')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tee_echos', to='patient.patient', verbose_name='بیمار')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tee_echos', to='prescriptions.prescription', verbose_name='نسخه مربوطه')),
            ],
            options={
                'verbose_name': 'اکو مری (TEE)',
                'verbose_name_plural': 'اکوهای مری',
                'ordering': ['-created_at'],
            },
        ),
    ]
