# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='عنوان کوتاه برای بلاک زمانی (مثال: مرخصی تابستانی).', max_length=255, verbose_name='عنوان بلاک')),
                ('type', models.CharField(choices=[('doctor_leave', 'مرخصی پزشک'), ('meeting', 'جلسه/کنفرانس'), ('equipment_maintenance', 'تعمیر تجهیزات'), ('other', 'سایر')], max_length=50, verbose_name='نوع بلاک')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع بلاک')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان بلاک')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بلاک زمانی',
                'verbose_name_plural': 'بلاک\u200cهای زمانی',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_code', models.CharField(max_length=20, unique=True, verbose_name='شماره نظام پزشکی')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='آدرس اینترنتی')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='مدرک تحصیلی')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='دانشگاه محل تحصیل')),
                ('work_experience', models.PositiveIntegerField(default=0, verbose_name='تجربه کاری (سال)')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='برچسب\u200cها (با ویرگول)')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('clinic_address', models.TextField(blank=True, verbose_name='آدرس مطب')),
                ('clinic_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن مطب')),
                ('clinic_location', models.CharField(blank=True, max_length=255, verbose_name='موقعیت مکانی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/profiles/', verbose_name='تصویر پروفایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], help_text='روزی از هفته که پزشک در آن فعال است (0=شنبه, 6=جمعه).', verbose_name='روز هفته')),
                ('start_time', models.TimeField(help_text='ساعت شروع شیفت کاری.', verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(help_text='ساعت پایان شیفت کاری.', verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این شیفت کاری در حال حاضر فعال است؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'برنامه کاری پزشک',
                'verbose_name_plural': 'برنامه\u200cهای کاری پزشکان',
                'ordering': ['doctor', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان تخصص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='آدرس اینترنتی')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته تخصص',
                'verbose_name_plural': 'دسته\u200cهای تخصص',
            },
        ),
    ]
