# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktime',
            name='location',
            field=models.ForeignKey(blank=True, help_text='اختیاری: اگر بلاک برای یک شعبه خاص است (و نه کل سیستم).', null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.location', verbose_name='شعبه مرتبط'),
        ),
        migrations.AddField(
            model_name='blocktime',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='اختیاری: اگر بلاک برای یک منبع خاص است (مثلاً اتاق، دستگاه).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='reception.resource', verbose_name='منبع مرتبط'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='شعبی که این پزشک در آن\u200cها فعالیت می\u200cکند.', to='reception.location', verbose_name='شعب فعالیت'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='blocktime',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='اختیاری: اگر بلاک برای یک پزشک خاص است.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='doctors.doctor', verbose_name='پزشک مرتبط'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='پزشک'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.location', verbose_name='شعبه فعالیت'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialty', verbose_name='تخصص'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialtycategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddIndex(
            model_name='blocktime',
            index=models.Index(fields=['doctor', 'start_datetime', 'end_datetime'], name='doctors_blo_doctor__48708c_idx'),
        ),
        migrations.AddIndex(
            model_name='blocktime',
            index=models.Index(fields=['resource', 'start_datetime', 'end_datetime'], name='doctors_blo_resourc_694a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='blocktime',
            index=models.Index(fields=['location', 'start_datetime', 'end_datetime'], name='doctors_blo_locatio_a9d436_idx'),
        ),
        migrations.AddIndex(
            model_name='blocktime',
            index=models.Index(fields=['type'], name='doctors_blo_type_325d50_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctor', 'location', 'day_of_week'], name='doctors_doc_doctor__c97150_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['start_time', 'end_time'], name='doctors_doc_start_t_64840b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['is_active'], name='doctors_doc_is_acti_6e0185_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['medical_code'], name='doctors_doc_medical_1f88cc_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty'], name='doctors_doc_special_b4a92b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='doctors_doc_is_acti_3a5153_idx'),
        ),
    ]
