# Generated by Django 5.2.4 on 2025-07-27 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP استاندارد'), ('SendGrid', 'SendGrid'), ('Mailgun', 'Mailgun'), ('AmazonSES', 'Amazon SES'), ('Other', 'سایر')], default='SMTP', max_length=50, verbose_name='سرویس\u200cدهنده')),
                ('host', models.CharField(max_length=255, verbose_name='آدرس سرور (Host)')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='پورت')),
                ('username', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('from_email', models.EmailField(help_text='مثال: no-reply@example.com', max_length=254, verbose_name='آدرس فرستنده')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS فعال باشد؟')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL فعال باشد؟')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='زمان انتظار (ثانیه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات ایمیل',
                'verbose_name_plural': 'تنظیمات ایمیل',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='IPPanel', max_length=50, verbose_name='سرویس\u200cدهنده')),
                ('api_key', models.CharField(max_length=255, verbose_name='کلید API')),
                ('originator', models.CharField(max_length=15, verbose_name='شماره فرستنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
        migrations.CreateModel(
            name='SMSPatternType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد یکتا')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع پترن پیامک',
                'verbose_name_plural': 'نوع\u200cهای پترن پیامک',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد قالب')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subject_template', models.CharField(max_length=255, verbose_name='قالب عنوان')),
                ('body_template', models.TextField(help_text='مثلاً: سلام {{ name }}، رمز شما {{ code }} است.', verbose_name='قالب متن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='clinic_messenger.emailconfig', verbose_name='تنظیمات ارسال')),
            ],
            options={
                'verbose_name': 'قالب ایمیل',
                'verbose_name_plural': 'قالب\u200cهای ایمیل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='گیرنده')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن')),
                ('purpose', models.CharField(choices=[('verify', 'تأیید ایمیل'), ('notify', 'اعلان سیستمی'), ('marketing', 'تبلیغاتی'), ('manual', 'ارسال دستی')], default='manual', max_length=20, verbose_name='نوع ایمیل')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('response_message', models.TextField(blank=True, verbose_name='پاسخ سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='clinic_messenger.emailconfig', verbose_name='تنظیمات ارسال')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='clinic_messenger.emailtemplate', verbose_name='قالب استفاده شده')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کدی که از IPPanel دریافت می\u200cکنید، مثل: mhq25jydcgqefq3', max_length=100, unique=True, verbose_name='کد پترن (از پنل پیامک)')),
                ('name', models.CharField(help_text='مثلاً: احراز هویت، تایید نوبت، یادآوری', max_length=100, verbose_name='عنوان داخلی')),
                ('provider', models.CharField(default='IPPanel', help_text='نام سرویس\u200cدهنده پیامک، مثلاً IPPanel یا Kavenegar', max_length=50, verbose_name='سرویس\u200cدهنده')),
                ('body_template', models.TextField(blank=True, help_text='فقط برای نمایش ساختار؛ پیام واقعی از طرف پنل ارسال می\u200cشود', verbose_name='نمایش ساختار پیام (فقط جهت مشاهده)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='clinic_messenger.smsconfig', verbose_name='تنظیمات ارسال')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns', to='clinic_messenger.smspatterntype', verbose_name='نوع پترن')),
            ],
            options={
                'verbose_name': 'پترن پیامک',
                'verbose_name_plural': 'پترن\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=15, verbose_name='شماره گیرنده')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('purpose', models.CharField(choices=[('otp', 'کد تایید'), ('notify', 'اطلاع\u200cرسانی'), ('marketing', 'تبلیغاتی'), ('manual', 'دستی')], default='manual', max_length=20, verbose_name='نوع پیام')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('response_message', models.TextField(blank=True, verbose_name='پاسخ سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='clinic_messenger.smsconfig', verbose_name='تنظیم ارسال')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='clinic_messenger.smspattern', verbose_name='پترن استفاده شده')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=10, verbose_name='کد تأیید')),
                ('purpose', models.CharField(choices=[('verify', 'تأیید شماره موبایل'), ('login', 'ورود با موبایل'), ('reset', 'فراموشی رمز عبور'), ('2fa', 'ورود دو مرحله\u200cای')], max_length=10, verbose_name='کاربرد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('expired', 'منقضی شده'), ('verified', 'تأیید شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست\u200cدهنده')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_codes', to='clinic_messenger.smsconfig', verbose_name='تنظیم ارسال پیامک')),
                ('sms_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_code', to='clinic_messenger.smsmessage', verbose_name='پیامک مربوطه')),
            ],
            options={
                'verbose_name': 'کد OTP',
                'verbose_name_plural': 'کدهای OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'code'], name='clinic_mess_phone_n_f43a36_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSPatternVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='نام متغیر')),
                ('label', models.CharField(max_length=100, verbose_name='عنوان نمایشی')),
                ('data_type', models.CharField(choices=[('string', 'متن'), ('int', 'عدد صحیح'), ('datetime', 'تاریخ/زمان'), ('phone', 'شماره موبایل')], default='string', max_length=20, verbose_name='نوع داده')),
                ('required', models.BooleanField(default=True, verbose_name='اجباری است؟')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='توضیح برای فرم یا اپراتور')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='clinic_messenger.smspattern', verbose_name='پترن مرتبط')),
            ],
            options={
                'verbose_name': 'متغیر پترن پیامک',
                'verbose_name_plural': 'متغیرهای پترن پیامک',
                'unique_together': {('pattern', 'key')},
            },
        ),
    ]
