# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAppointmentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('bi_weekly', 'دو هفته یکبار'), ('monthly', 'ماهانه'), ('yearly', 'سالانه'), ('custom', 'سفارشی')], help_text='نوع تکرار نوبت\u200cها (مثلاً هفتگی، ماهانه).', max_length=20, verbose_name='نوع تکرار')),
                ('recurrence_value', models.CharField(blank=True, help_text="مقدار مرتبط با نوع تکرار (مثلاً '0,2,4' برای شنبه، دوشنبه، چهارشنبه؛ یا '15' برای پانزدهم هر ماه).", max_length=50, null=True, verbose_name='مقدار تکرار')),
                ('start_date', models.DateField(help_text='تاریخ شروع اولین نوبت از این سری.', verbose_name='تاریخ شروع سری')),
                ('end_date', models.DateField(blank=True, help_text='تاریخ پایان آخرین نوبت از این سری (اختیاری، می\u200cتواند نامحدود باشد).', null=True, verbose_name='تاریخ پایان سری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('paused', 'متوقف'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='active', help_text='وضعیت فعلی سری نوبت\u200cهای تکراری.', max_length=20, verbose_name='وضعیت سری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سری نوبت تکراری',
                'verbose_name_plural': 'سری\u200cهای نوبت تکراری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='توضیحات یا ملاحظات اضافی از طرف بیمار.', null=True, verbose_name='یادداشت بیمار')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('offered', 'نوبت پیشنهاد شده'), ('booked', 'نوبت رزرو شد'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', help_text='وضعیت فعلی درخواست در لیست انتظار.', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('offered_at', models.DateTimeField(blank=True, help_text='زمانی که نوبتی به بیمار پیشنهاد شده است.', null=True, verbose_name='زمان پیشنهاد نوبت')),
            ],
            options={
                'verbose_name': 'ورودی لیست انتظار',
                'verbose_name_plural': 'ورودی\u200cهای لیست انتظار',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='تاریخ برنامه\u200cریزی شده برای نوبت.', verbose_name='تاریخ نوبت')),
                ('time', models.TimeField(help_text='ساعت شروع نوبت (مثلاً ۰۹:۰۰).', verbose_name='ساعت شروع نوبت')),
                ('end_time', models.TimeField(blank=True, help_text='ساعت پایان نوبت (بر اساس مدت زمان خدمت محاسبه می\u200cشود).', null=True, verbose_name='ساعت پایان نوبت')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='مدت زمان تخمینی برای این نوبت (کپی شده از نوع خدمت).', null=True, verbose_name='مدت زمان تخمینی (دقیقه)')),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, help_text='مدت زمان واقعی که نوبت طول کشید (پس از انجام).', null=True, verbose_name='مدت زمان واقعی (دقیقه)')),
                ('method', models.CharField(choices=[('phone', 'تلفنی'), ('in_person', 'حضوری'), ('online', 'آنلاین'), ('walk_in', 'مراجعه فوری')], default='online', help_text='روشی که بیمار برای نوبت اقدام کرده است.', max_length=50, verbose_name='نحوه پذیرش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('booked', 'رزرو شده'), ('confirmed', 'تایید شده'), ('check_in', 'حضور یافته'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('canceled', 'لغو شده'), ('no_show', 'عدم حضور'), ('rescheduled', 'تغییر زمان داده شده'), ('rejected', 'رد شده'), ('pending_payment', 'در انتظار پرداخت')], default='booked', help_text='وضعیت فعلی این نوبت در چرخه حیات آن.', max_length=50, verbose_name='وضعیت نوبت')),
                ('status_changed_at', models.DateTimeField(blank=True, help_text='آخرین زمان تغییر وضعیت نوبت.', null=True, verbose_name='زمان آخرین تغییر وضعیت')),
                ('cancellation_reason', models.TextField(blank=True, help_text='دلیل لغو شدن نوبت یا رد شدن آن.', null=True, verbose_name='دلیل لغو/رد')),
                ('reschedule_count', models.PositiveIntegerField(default=0, help_text='تعداد دفعاتی که این نوبت تغییر زمان داده است.', verbose_name='تعداد دفعات تغییر زمان')),
                ('tracking_code', models.CharField(blank=True, editable=False, help_text='کد یکتا برای پیگیری این نوبت توسط بیمار یا منشی.', max_length=100, null=True, unique=True, verbose_name='کد رهگیری یکتا')),
                ('is_recurrent', models.BooleanField(default=False, help_text='آیا این نوبت بخشی از یک سری نوبت\u200cهای تکراری است؟', verbose_name='نوبت تکراری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='زمانی که بیمار برای این نوبت وارد کلینیک شده است.', null=True, verbose_name='زمان ورود به کلینیک')),
                ('service_start_time', models.DateTimeField(blank=True, help_text='زمانی که ارائه خدمت به بیمار عملاً آغاز شده است.', null=True, verbose_name='زمان شروع واقعی خدمت')),
                ('service_end_time', models.DateTimeField(blank=True, help_text='زمانی که ارائه خدمت به بیمار عملاً به پایان رسیده است.', null=True, verbose_name='زمان پایان واقعی خدمت')),
                ('patient_notes', models.TextField(blank=True, help_text='یادداشت\u200cها یا درخواست\u200cهای خاصی که بیمار ممکن است داشته باشد.', null=True, verbose_name='یادداشت\u200cهای بیمار')),
                ('internal_notes', models.TextField(blank=True, help_text='یادداشت\u200cها و توضیحات برای استفاده داخلی پرسنل (مثلاً پیگیری).', null=True, verbose_name='یادداشت\u200cهای داخلی سیستم/ادمین')),
                ('priority_number', models.PositiveIntegerField(blank=True, help_text='شماره نوبت در صف برای همان زمان و پزشک/خدمت.', null=True, verbose_name='شماره اولویت/صف')),
                ('created_by', models.ForeignKey(blank=True, help_text='کاربری که این نوبت را ثبت کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['date', 'time'],
            },
        ),
    ]
