# Generated by Django 5.2.4 on 2025-07-27 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(help_text='پزشکی که نوبت با او رزرو شده است.', on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor', verbose_name='پزشک'),
        ),
    ]
